<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>justing-cloud</artifactId>
        <groupId>org.liu</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloud-common</artifactId>
    <packaging>pom</packaging>

    <description>公共聚合模块</description>

    <modules>
        <module>cloud-common-core</module>
        <module>cloud-common-feign</module>
        <module>cloud-common-cache</module>
        <module>cloud-common-codegenerator</module>
        <module>cloud-common-service</module>
        <module>cloud-common-security-resource-server</module>
        <module>cloud-common-security-base</module>
    </modules>

</project>
