<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<modules>
		<module>cloud-public</module>
		<module>cloud-config-server</module>
		<module>cloud-eureka</module>
		<module>cloud-order</module>
		<module>cloud-user</module>
		<module>cloud-zuul</module>
        <module>cloud-storage</module>
		<module>cloud-common</module>
        <module>cloud-flow</module>
		<module>cloud-activity</module>
		<module>cloud-product</module>
	</modules>

	<groupId>org.liu</groupId>
	<artifactId>justing-cloud</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<java.version>1.8</java.version>
		<spring-boot.version>2.3.0.RELEASE</spring-boot.version>
		<spring-cloud.version>Hoxton.SR4</spring-cloud.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!--springboot,springcloud-->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!--限流-->
			<dependency>
				<groupId>com.marcosbarbero.cloud</groupId>
				<artifactId>spring-cloud-zuul-ratelimit</artifactId>
				<version>2.4.1.RELEASE</version>
			</dependency>
			<!--公共模块-->
			<dependency>
				<groupId>org.justing.commons</groupId>
				<artifactId>justing-commons-util</artifactId>
				<version>1.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>org.justing.commons</groupId>
				<artifactId>justing-commons-base</artifactId>
				<version>1.0-SNAPSHOT</version>
			</dependency>
			<!--**********项目自身的模块********start-->
			<!--项目内公共聚合模块-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-common-core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--配置中心-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-config-server</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--服务发现-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-eureka</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--订单-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--基础服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--库存服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--用户服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--zuul网关服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-zuul</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--**********项目自身的模块********end-->
		</dependencies>
	</dependencyManagement>

</project>
