<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<modules>
		<module>cloud-activity</module>
		<module>cloud-admin</module>
		<module>cloud-auth</module>
		<module>cloud-common</module>
		<module>cloud-config-server</module>
		<module>cloud-coupon</module>
		<module>cloud-eureka</module>
		<module>cloud-flow</module>
		<module>cloud-gateway</module>
		<module>cloud-order</module>
		<module>cloud-product</module>
		<module>cloud-public</module>
		<module>cloud-search</module>
		<module>cloud-storage</module>
		<module>cloud-user</module>
		<module>cloud-zuul</module>
	</modules>

	<groupId>org.liu</groupId>
	<artifactId>justing-cloud</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-boot.version>2.3.12.RELEASE</spring-boot.version>
		<spring-cloud.version>Hoxton.SR12</spring-cloud.version>
		<seata.version>2.1.0.RELEASE</seata.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!--springboot,springcloud-->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!--分布式事务-->
			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-starter-alibaba-seata</artifactId>
				<version>${seata.version}</version>
			</dependency>
			<!--限流-->
			<dependency>
				<groupId>com.marcosbarbero.cloud</groupId>
				<artifactId>spring-cloud-zuul-ratelimit</artifactId>
				<version>2.4.1.RELEASE</version>
			</dependency>
			<!--持久层框架-->
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-boot-starter</artifactId>
				<version>3.3.0</version>
			</dependency>
			<!--跨项目通用模块-->
			<dependency>
				<groupId>org.justing.commons</groupId>
				<artifactId>justing-commons-util</artifactId>
				<version>1.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>org.justing.commons</groupId>
				<artifactId>justing-commons-base</artifactId>
				<version>1.0-SNAPSHOT</version>
			</dependency>
			<!--**********项目自身的模块********start-->
			<!--活动服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-activity</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-activity-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-activity-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-activity-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--管理后台权限服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-admin</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-admin-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-admin-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-admin-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--授权服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-auth</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--项目内公共聚合模块-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-common-cache</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-common-core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-common-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--配置中心-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-config-server</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--优惠券服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-coupon</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-coupon-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-coupon-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-coupon-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--服务发现-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-eureka</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--流程服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-flow</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-flow-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-flow-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-flow-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--spring cloud gateway-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-gateway</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--订单服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-order-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--产品服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-product</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-product-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-product-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-product-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--基础服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-public-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--搜索服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-search</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-search-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-search-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-search-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--库存服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-storage-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--用户服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user-feign</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user-feign-pojo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-user-service</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--zuul网关服务-->
			<dependency>
				<groupId>org.liu</groupId>
				<artifactId>cloud-zuul</artifactId>
				<version>${project.version}</version>
			</dependency>
			<!--**********项目自身的模块********end-->
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<version>${spring-boot.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

<!--	<repositories>-->
<!--		<repository>-->
<!--			<id>jxmx-nexus</id>-->
<!--			<name>jxmx nexus</name>-->
<!--			<layout>default</layout>-->
<!--			<url>http://192.168.0.201:8681/repository/maven-public/</url>-->
<!--			<snapshots>-->
<!--				<enabled>true</enabled>-->
<!--				<updatePolicy>always</updatePolicy>-->
<!--			</snapshots>-->
<!--			<releases>-->
<!--				<enabled>true</enabled>-->
<!--			</releases>-->
<!--		</repository>-->
<!--	</repositories>-->
<!--	<pluginRepositories>-->
<!--		<pluginRepository>-->
<!--			<id>jxmx-nexus-plugin</id>-->
<!--			<name>jxmx nexus plugin</name>-->
<!--			<url>http://192.168.0.201:8681/repository/maven-public/</url>-->
<!--			<releases>-->
<!--				<enabled>true</enabled>-->
<!--			</releases>-->
<!--			<snapshots>-->
<!--				<enabled>false</enabled>-->
<!--			</snapshots>-->
<!--		</pluginRepository>-->
<!--	</pluginRepositories>-->

	<distributionManagement>
		<snapshotRepository>
			<id>jxmx-snapshot</id>
			<url>http://192.168.0.201:8681/repository/maven-snapshots/</url>
		</snapshotRepository>
		<repository>
			<id>jxmx-release</id>
			<url>http://192.168.0.201:8681/repository/maven-releases/</url>
		</repository>
	</distributionManagement>

</project>
