<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>justing-cloud</artifactId>
        <groupId>org.liu</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloud-auth</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <dependencies>
        <!--spring-boot依赖-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <!--spring-cloud依赖-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-oauth2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
        </dependency>
        <!--数据源-->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!--引入其他服务的feign，保留版本号，不使用顶级pom管理，因为随着项目的演变，各微服务会各自发展-->
        <dependency>
            <groupId>org.liu</groupId>
            <artifactId>cloud-admin-feign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liu</groupId>
            <artifactId>cloud-wx-feign</artifactId>
        </dependency>
        <!--跨项目通用模块-->
        <dependency>
            <groupId>org.justing.commons</groupId>
            <artifactId>justing-commons-util</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <!--项目内部的基础模块-->
        <dependency>
            <groupId>org.liu</groupId>
            <artifactId>cloud-common-security-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liu</groupId>
            <artifactId>cloud-common-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liu</groupId>
            <artifactId>cloud-common-cors</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>