<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cloud-common</artifactId>
        <groupId>org.liu</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cloud-common-feign</artifactId>

    <dependencies>
        <!--此处是只依赖feign相关的jar，还是依赖spring-cloud-starter-openfeign，有待考究？？？
        如果此common-feign只在项目内部使用，则依赖spring-cloud-starter-openfeign较好
        如果此common-feign模块也会给外部项目依赖，则使用最小依赖原则，只依赖feign相关的jar，
        这两个原则对各个子服务的feign模块也适应
        -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </dependency>

        <!--内部模快-->
        <dependency>
            <groupId>org.liu</groupId>
            <artifactId>cloud-common-core</artifactId>
        </dependency>

        <!--optional依赖-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
